# Generated by Django 5.2.15 on 2026-07-09 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip', 'docx', 'png', 'jpg', 'jpeg', 'txt'])]),
        ),
    ]
