# Generated by Django 5.2.15 on 2026-07-14 03:47

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectrequest_file_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/', validators=[utils.validators.validate_file_security]),
        ),
    ]
