# Generated by Django 5.2.15 on 2026-07-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(default='Web Development', max_length=50)),
            ],
        ),
    ]
