# Generated by Django 5.2.15 on 2026-07-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='github_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='live_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='technologies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
