# Generated by Django 5.2.15 on 2026-07-14 03:47

import django.db.models.deletion
import utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyfile',
            name='file',
            field=models.FileField(upload_to='agency_files/', validators=[utils.validators.validate_file_security]),
        ),
        migrations.AlterField(
            model_name='agencyfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
