# Generated by Django 5.2.15 on 2026-07-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_files', '0002_alter_agencyfile_file_alter_agencyfile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
