# Generated by Django 5.2.15 on 2026-07-14 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('projects', '0003_alter_projectrequest_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='project_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='projects.projectrequest'),
        ),
    ]
